name: NextJs Build with Cache and Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup NodeJs
        uses: actions/setup-node@b6.0.0
        with:
          node-version: 22.x
          cache:  'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build the App
        run: npm run build

      - name: Store Build on Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: NextJs-Build
          path: out/

          
          
